using UnityEngine;

public class RacketSweetSpotOval : MonoBehaviour
{
    
    public enum StringAlignment { XY_Plane, XZ_Plane, YZ_Plane }
    
    [Header("Orientation")]
    [Tooltip("Which local axes represent the flat surface of your strings? Look at the transform arrows on your racket.")]
    public StringAlignment stringPlane = StringAlignment.XY_Plane;

    [Header("Racket Setup")] [Tooltip("Drag the child GameObject that has your Strings Collider here.")]
    public Collider stringsCollider;
    
    [Header("Bounce & Swing Physics")]
    [Tooltip("The default speed the shuttlecock bounces off if the racket is completely still.")]
    public float baseRestingBounce = 5f;
    
    [Tooltip("How much of your swing speed is transferred to the shuttlecock? (1 = 100%, 1.5 = 150%)")]
    public float swingPowerTransfer = 1.2f;

    [Header("Sweet Spot Multipliers")]
    [Tooltip("Multiplier applied to the final speed when hitting dead center.")]
    public float maxSweetSpotMultiplier = 1.5f;
    [Tooltip("Multiplier applied to the final speed when hitting the edge of the frame.")]
    public float minSweetSpotMultiplier = 0.4f;
    
    [Header("Racket Dimensions (Local Space)")]
    [Tooltip("The horizontal radius (width / 2) of the strings.")]
    public float radiusWidth = 0.11f; 
    
    [Tooltip("The vertical radius (height / 2) of the strings.")]
    public float radiusHeight = 0.15f; 
    
    private float lastHitTime = 0f;
    private float hitCooldown = 0.05f;
    private Rigidbody racketRb;
    
    private void Start()
    {
        // Grab the Rigidbody on this parent racket object
        racketRb = GetComponent<Rigidbody>();
    }

    private void OnCollisionEnter(Collision collision)
    {
        Debug.Log($"<b><color=cyan>[Racket Hit]</color></b> " + "Collision entered");
        if (collision.gameObject.CompareTag("Volant"))
        {
            if (Time.time - lastHitTime < hitCooldown) return;

            if (collision.GetContact(0).thisCollider != stringsCollider) return; 

            Transform sTransform = stringsCollider.transform;
            Vector3 impactPoint = collision.GetContact(0).point;
            Vector3 localImpact = sTransform.InverseTransformPoint(impactPoint);

            float localW = 0f;
            float localH = 0f;
            Vector3 rawFaceNormal = Vector3.zero;

            switch (stringPlane)
            {
                case StringAlignment.XY_Plane:
                    localW = localImpact.x; localH = localImpact.y; rawFaceNormal = sTransform.forward; break;
                case StringAlignment.XZ_Plane:
                    localW = localImpact.x; localH = localImpact.z; rawFaceNormal = sTransform.up; break;
                case StringAlignment.YZ_Plane:
                    localW = localImpact.y; localH = localImpact.z; rawFaceNormal = sTransform.right; break;
            }

            Vector3 directionToShuttle = collision.transform.position - sTransform.position;
            Vector3 finalHitDirection = rawFaceNormal;
            string strokeType = "Forehand";
            
            if (Vector3.Dot(rawFaceNormal, directionToShuttle) < 0)
            {
                finalHitDirection = -rawFaceNormal; 
                strokeType = "Backhand";
            }

            // --- 1. SWEET SPOT CALCULATION ---
            float wRatio = localW / radiusWidth;
            float hRatio = localH / radiusHeight;
            float distanceRatio = Mathf.Clamp01(Mathf.Sqrt((wRatio * wRatio) + (hRatio * hRatio)));
            float powerMultiplier = 1f - distanceRatio;
            float currentSweetSpotMult = Mathf.Lerp(minSweetSpotMultiplier, maxSweetSpotMultiplier, powerMultiplier);

            // --- 2. NEW SWING SPEED MATH ---
            float swingSpeed = 0f;
            if (racketRb != null)
            {
                // Get the exact speed of the racket at the spot where the strings hit the bird
                Vector3 racketVelocityAtImpact = racketRb.GetPointVelocity(impactPoint);
                
                // Project that velocity to see how fast we were swinging FORWARD into the bird
                swingSpeed = Vector3.Dot(racketVelocityAtImpact, finalHitDirection);
                
                // If we are pulling the racket backward away from the bird, ignore the negative speed
                swingSpeed = Mathf.Max(0f, swingSpeed);
            }

            // --- 3. FINAL OUTPUT CALCULATION ---
            // Base speed + whatever speed we generated by swinging, multiplied by the sweet spot!
            float rawOutputSpeed = baseRestingBounce + (swingSpeed * swingPowerTransfer);
            float finalSpeed = rawOutputSpeed * currentSweetSpotMult;

            Rigidbody shuttleRb = collision.gameObject.GetComponent<Rigidbody>();
            if (shuttleRb != null)
            {
                Debug.Log($"<b><color=orange>[{strokeType} Hit]</color></b> " +
                          $"Swing Speed: {swingSpeed:F2} | " +
                          $"Raw Output: {rawOutputSpeed:F2} | " +
                          $"SweetSpot: x{currentSweetSpotMult:F2} | " +
                          $"<b>Final Speed: {finalSpeed:F2}</b>");

                Debug.DrawRay(impactPoint, finalHitDirection * 0.5f, Color.green, 2f);

                shuttleRb.linearVelocity = Vector3.zero;
                shuttleRb.AddForce(finalHitDirection * finalSpeed, ForceMode.VelocityChange);
                lastHitTime = Time.time;
            }
        }
    }
    
    private void OnDrawGizmosSelected()
    {
        // We only draw if you've assigned the strings!
        if (stringsCollider == null) return;

        Transform sTransform = stringsCollider.transform;
        
        // 1. Draw the dead center (Sweetest Spot) in Red
        Gizmos.color = Color.red;
        Gizmos.DrawSphere(sTransform.position, 0.01f);

        // 2. Draw the outer edge of the sweet spot in Green
        Gizmos.color = Color.green;
        
        int segments = 36; // How smooth the drawn oval will be
        float angle = 0f;
        Vector3 previousPoint = Vector3.zero;

        for (int i = 0; i <= segments; i++)
        {
            // Calculate the local X and Y for this segment of the ellipse
            float w = Mathf.Sin(angle) * radiusWidth;
            float h = Mathf.Cos(angle) * radiusHeight;
            
            Vector3 localPoint = Vector3.zero;

            // Map the drawn points to the correct axes
            switch (stringPlane)
            {
                case StringAlignment.XY_Plane: localPoint = new Vector3(w, h, 0f); break;
                case StringAlignment.XZ_Plane: localPoint = new Vector3(w, 0f, h); break;
                case StringAlignment.YZ_Plane: localPoint = new Vector3(0f, w, h); break;
            }
            
            // Convert that local point into world space so it rotates with the racket
            // Assuming the strings face the Z-axis, we draw flat on X and Y
            Vector3 currentPoint = sTransform.TransformPoint(localPoint);

            // Draw a line connecting the previous point to the current point
            if (i > 0)
            {
                Gizmos.DrawLine(previousPoint, currentPoint);
            }

            previousPoint = currentPoint;
            angle += (Mathf.PI * 2f) / segments; // Move to the next slice of the pie
        }
    }
}